export const COMPAGO_USER_SECURITY_CREDENTIALS: string = "COMPAGO_USER_SECURITY_CREDENTIALS";
export const COMPAGO_LOGOUT_INFO: string = "COMPAGO_LOGOUT_INFO";
export const COMPAGO_PAGE_LOGOUT_RELOAD: string = "COMPAGO_PAGE_LOGOUT_RELOAD";