name: Code analysis

on:
  push:
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup vite/node
        run: |
          npm install vite@7.1.7
          npm install node@24.6.0
      - name: Build
        run: |
          npm run build